### ISSUE TITLE
saveFile fils with empty signal

### ISSUE THREAD

**Issue by hagenw** [TWOEARS/binaural-simulator#8]
I was testing the tutorial example:
http://twoears.aipa.tu-berlin.de/doc/latest/intro/tutorial-acoustic-scene/#binaural-renderer

The following commands work great:
```Matlab
>> sim = simulator.SimulatorConvexRoom('binaural_renderer.xml');
>> sim.set('Init',true);
Starting the SSR with following settings:
 * number of sources: 1
 * block_size: 4096
 * delayline_size: 0
 * hrir_file: /home/hagen/git/twoears/twoears-wp1/src/+xml/../../tmp/QU_KEMAR_anechoic_3m_tp7be417cc_52c0_4dbc_a041_f6e4b0d51c38.wav
 * initial_delay: 0
 * sample_rate: 44100
 * threads: 1
Initialization of BinauralRenderer completed, 2 outputs available.
>> signal = sim.getSignal();
>> size(signal)

ans =

      450560           2
```

If I do the same with the `saveFile` function as proposed in the example it fails:
```Matlab
>> sim = simulator.SimulatorConvexRoom('binaural_renderer.xml');
>> sim.set('Init',true);
Starting the SSR with following settings:
 * number of sources: 1
 * block_size: 4096
 * delayline_size: 0
 * hrir_file: /home/hagen/git/twoears/twoears-wp1/src/+xml/../../tmp/QU_KEMAR_anechoic_3m_tpdeda73ed_5de5_46dd_bb26_2b2f6a64e547.wav
 * initial_delay: 0
 * sample_rate: 44100
 * threads: 1
Initialization of BinauralRenderer completed, 2 outputs available.
>> sim.Sinks.saveFile('binaural_renderer.wav',sim.SampleRate);  
Error using ./
Matrix dimensions must agree.

Error in simulator.buffer.Data/saveFile (line 117)
      audiowrite(filename, tmp./max(abs(tmp(:))), fs);  % normalize data
```

If you debug, you will find that `size(tmp)` is `[0 0]`.

**Comment by fietew** [comment]
1. You are not doing the same: ``sim.getSignal()`` processes the binaural signal, while in the second code snippets the simulator is just initialized and does nothing afterwards. Hence, the buffer of the sink is empty.
2. Yes, an empty buffer should be handled somehow in ``.saveFile`` in order to give a more meaningful error message

**Comment by hagenw** [comment]
If I would do the following steps should it then work as I process the signal in between?

```Matlab
sim = simulator.SimulatorConvexRoom('binaural_renderer.xml');
sim.set('Init',true);
signal = sim.getSignal();
sim.Sinks.saveFile('binaural_renderer.wav',sim.SampleRate);  
```

**Comment by hagenw** [comment]
For me it returns the same error.

**Comment by fietew** [comment]
Yeah, I agree, the documentation is wrong at this point. If you use the sim.getSignal(), the buffer of the sink is emptied automatically. Since, it does yield the same error. So, second bug: documentation.

**Comment by hagenw** [comment]
OK, could you please update the documentation and add a good error message to `.saveFile` for the cases of an empty buffer.
